version: '3.3'

services:
  db:
    image: postgres:16.0-alpine
    container_name: db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-foodgram}
      POSTGRES_USER: ${POSTGRES_USER:-foodgram_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foodgram_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-foodgram_user} -d ${POSTGRES_DB:-foodgram}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    image: 292004/foodgram_yandex_backend
    container_name: backend
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB:-foodgram}
      POSTGRES_USER: ${POSTGRES_USER:-foodgram_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-foodgram_password}
      SECRET_KEY: ${SECRET_KEY:-django-insecure-key}
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: 292004/foodgram_yandex_frontend
    container_name: frontend
    volumes:
      - build_volume:/app/frontbuild/

  nginx:
    image: nginx:1.25.4-alpine
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx_deploy.conf:/etc/nginx/conf.d/default.conf
      - build_volume:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  build_volume:
  static_volume:
  media_volume: