MEASUREMENT_UNIT_DEFAULT = "g"
RECIPE_NAME_MAX_LENGTH = 200
COOKING_TIME_MIN_VALUE = 1
COOKING_TIME_MIN_VALUE_ERROR_MESSAGE = "Время приготовления не может быть меньше 1"
AMOUNT_MIN_VALUE = 1
RECIPE_IMAGE_UPLOAD_TO = "recipes/"
AMOUNT_MIN_VALUE_ERROR_MESSAGE = "Не может быть меньше 1"
MAX_FIELD_LENGTH = 256
