INGREDIENT_NAME_MAX_LENGTH = 80
MEASUREMENT_UNIT_MAX_LENGTH = 50
MEASUREMENT_UNIT_DEFAULT = "g"
RECIPE_NAME_MAX_LENGTH = 200
COOKING_TIME_MIN_VALUE = 1
AMOUNT_MIN_VALUE = 1
RECIPE_IMAGE_UPLOAD_TO = "recipes/"
